name: Generate Protobuf & gRPC Stubs

on: [push, pull_request]

jobs:
  vm-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: rm -rf gen
      - run: docker run -v "$(pwd):/work" uber/prototool:latest prototool break check
      - run: docker run -v "$(pwd):/work" uber/prototool:latest prototool format -f -w
      - run: docker run -v "$(pwd):/work" uber/prototool:latest prototool generate proto
      - run: sudo ls -l
