name: Generate Protobuf & gRPC Stubs

on: [push, pull_request]

jobs:
  vm-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker run namely/prototool version
